trigger:
  - main
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Tell the server to use .NET 8
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

# Step 2: Build the entire solution (.sln)
- task: DotNetCoreCLI@2
  displayName: 'Build the Solution'
  inputs:
    command: 'build'
    projects: '**/*.slnx'
    arguments: '--configuration $(buildConfiguration)'

# Step 3: Find and run the xUnit tests
- task: DotNetCoreCLI@2
  displayName: 'Run Unit and Integration Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'