//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLib.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameCategoryTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameCategoryTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLib.App.Resources.Texts.GameCategoryTexts", typeof(GameCategoryTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        public static string Arcade {
            get {
                return ResourceManager.GetString("Arcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattleRoyale.
        /// </summary>
        public static string BattleRoyale {
            get {
                return ResourceManager.GetString("BattleRoyale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational.
        /// </summary>
        public static string Educational {
            get {
                return ResourceManager.GetString("Educational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        public static string Fighting {
            get {
                return ResourceManager.GetString("Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Horror {
            get {
                return ResourceManager.GetString("Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string Indie {
            get {
                return ResourceManager.GetString("Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMO.
        /// </summary>
        public static string MMO {
            get {
                return ResourceManager.GetString("MMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platformer.
        /// </summary>
        public static string Platformer {
            get {
                return ResourceManager.GetString("Platformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzles.
        /// </summary>
        public static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing.
        /// </summary>
        public static string Racing {
            get {
                return ResourceManager.GetString("Racing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolePlaying.
        /// </summary>
        public static string RolePlaying {
            get {
                return ResourceManager.GetString("RolePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rythm.
        /// </summary>
        public static string Rythm {
            get {
                return ResourceManager.GetString("Rythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        public static string Sandbox {
            get {
                return ResourceManager.GetString("Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter.
        /// </summary>
        public static string Shooter {
            get {
                return ResourceManager.GetString("Shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
    }
}
